module.exports={
    ContactForumRepository:require('./contactForum-repository'),
    DomainRepository:require('./domain-repository'),
    OfficialRepository:require('./officials-details-repository'),
    ProjectRepository:require('./project-repository'),
    ResourceRepository:require('./resources-repository'),
    UserRepository:require('./user-repository'),
    EventRepository:require('./event-repository')
}